//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceCenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int Id_orders { get; set; }
        public Nullable<System.DateTime> Data_Zakaza { get; set; }
        public Nullable<System.DateTime> Data_of_vozvrata { get; set; }
        public string FIO_Customers { get; set; }
        public string Serial_number { get; set; }
        public Nullable<int> id_Types_of_faults { get; set; }
        public Nullable<int> id_shop { get; set; }
        public string Otmetka_o_garanti { get; set; }
        public Nullable<System.DateTime> Srok_garanti_remonta { get; set; }
        public string Price { get; set; }
        public Nullable<int> id_empl { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Shop Shop { get; set; }
        public virtual Types_of_faults Types_of_faults { get; set; }
    }
}
